In [70]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.5.1+cu124


In [71]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


<h2>Introduction to Tensors</h2>

Scalar

In [72]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [73]:
scalar.ndim

0

In [74]:
scalar.item()

7

Vector

In [75]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [76]:
vector.ndim
# no of pairs of square brackets

1

In [77]:
vector.shape
# 2 by 1 elements

torch.Size([2])

Matrix

In [78]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [79]:
matrix.ndim

2

In [80]:
matrix[0], matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [81]:
matrix.shape

torch.Size([2, 2])

Tensor

In [82]:
tn = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tn

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [83]:
tn.ndim

3

In [84]:
tn.shape

torch.Size([1, 3, 3])

Creating a random tensor

In [85]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3686, 0.8281, 0.9737, 0.7176],
        [0.5479, 0.9274, 0.3354, 0.1242],
        [0.7117, 0.4353, 0.2075, 0.9886]])

In [86]:
random_tensor.ndim

2

In [87]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, no. of color channels
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.2161, 0.5879, 0.4903],
          [0.5778, 0.8739, 0.7024],
          [0.4938, 0.2191, 0.4000],
          ...,
          [0.9633, 0.4610, 0.8116],
          [0.8118, 0.8436, 0.0286],
          [0.8168, 0.8690, 0.8449]],
 
         [[0.4825, 0.1066, 0.9715],
          [0.5145, 0.2943, 0.3636],
          [0.2034, 0.5858, 0.3541],
          ...,
          [0.1497, 0.3268, 0.4932],
          [0.1509, 0.9787, 0.4779],
          [0.9473, 0.8605, 0.6922]],
 
         [[0.3316, 0.0224, 0.7659],
          [0.4636, 0.5986, 0.0751],
          [0.6305, 0.4579, 0.5113],
          ...,
          [0.3330, 0.4029, 0.2457],
          [0.5878, 0.0962, 0.4000],
          [0.0660, 0.1958, 0.1633]],
 
         ...,
 
         [[0.4426, 0.0018, 0.9599],
          [0.2779, 0.2204, 0.1541],
          [0.2201, 0.2618, 0.2820],
          ...,
          [0.5981, 0.7883, 0.0762],
          [0.8374, 0.2121, 0.6624],
          [0.6465, 0.2639, 0.5528]],
 
         [[0.5633, 0.2136, 0.9334],
          [0

Tensors with 0s and 1s

In [88]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [89]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
ones.dtype

torch.float32

In [91]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<h3>Tensor data-types</h3>

In [92]:
tensor_float_32 = torch.tensor([3.0,6.0,9.0],dtype=None)
tensor_float_32
tensor_float_32.dtype # more precision (single precision)

torch.float32

In [93]:
tensor_float_16 = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
tensor_float_16.dtype # less memory, faster calculation (half precision)

torch.float16

In [94]:
tensor_float_16 = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16, # what datatype is the tensor
                               device="cpu", # which device is the tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations

Changing dtype

In [95]:
tensor_float_16 = tensor_float_32.type(torch.half)
tensor_float_16.dtype

torch.float16

Precision: https://en.wikipedia.org/wiki/Precision_(computer_science)

<h3>Tensor Attributes</h3>



* tensor.dtype
* tensor.shape
* tensor.device



In [96]:
tensor = torch.rand(3,4)

In [97]:
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

<h3>Tensor Operations</h3>

In [98]:
tensor = torch.tensor([1,2,3])

Addition

In [99]:
tensor+10

tensor([11, 12, 13])

In [100]:
torch.add(tensor,10)

tensor([11, 12, 13])

Multiplication

In [101]:
tensor*10

tensor([10, 20, 30])

In [102]:
torch.mul(tensor,10)

tensor([10, 20, 30])

Subtraction

In [103]:
tensor-10

tensor([-9, -8, -7])

Matrix Multiplication



*   Element-wise multiplication: a scalar value is multiplied by each element in the matrix
*   Matrix multiplication: dot product



In [104]:
# element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [105]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

Inner dimensions must match for matmul

In [106]:
tensor1 = torch.rand(3,2)
tensor1

tensor([[0.1949, 0.6507],
        [0.9212, 0.8866],
        [0.9282, 0.4269]])

In [107]:
tensor1.shape

torch.Size([3, 2])

In [108]:
tensor2 = torch.rand(2,3)
tensor2

tensor([[0.2376, 0.6485, 0.8318],
        [0.1696, 0.3472, 0.9051]])

In [109]:
tensor2.shape

torch.Size([2, 3])

In [110]:
torch.matmul(tensor2,tensor1)

tensor([[1.4157, 1.0846],
        [1.1929, 0.8045]])

In [111]:
torch.matmul(tensor1,tensor2)

tensor([[0.1567, 0.3523, 0.7511],
        [0.3692, 0.9052, 1.5687],
        [0.2929, 0.7501, 1.1583]])

In [112]:
tensor3 = torch.rand(4,3)
tensor3, tensor3.shape

(tensor([[0.7447, 0.1910, 0.5963],
         [0.1107, 0.3636, 0.2617],
         [0.3518, 0.6782, 0.9697],
         [0.6294, 0.4944, 0.2056]]),
 torch.Size([4, 3]))

In [113]:
torch.matmul(tensor3,tensor1)

tensor([[0.8745, 0.9085],
        [0.5994, 0.5061],
        [1.5934, 1.2442],
        [0.7689, 0.9356]])

In [114]:
# torch.matmul(tensor3,tensor2)
# inner dimensions do not match
# (4x3 and 2x3)

Dealing with tensor shape errors: Transpose

In [115]:
tensor2.T

tensor([[0.2376, 0.1696],
        [0.6485, 0.3472],
        [0.8318, 0.9051]])

In [116]:
tensor2.T.shape

torch.Size([3, 2])

In [117]:
torch.matmul(tensor3,tensor2.T)

tensor([[0.7968, 0.7323],
        [0.4798, 0.3819],
        [1.3300, 1.1728],
        [0.6411, 0.4644]])

<h3>Tensor Aggregation</h3>

In [118]:
x = torch.rand(4,4)
x

tensor([[0.5764, 0.3028, 0.2594, 0.3727],
        [0.0359, 0.1020, 0.2792, 0.6929],
        [0.4388, 0.7658, 0.4224, 0.7634],
        [0.9089, 0.7659, 0.5871, 0.0122]])

In [119]:
# min
torch.min(x)

tensor(0.0122)

In [120]:
# max
torch.max(x)

tensor(0.9089)

In [121]:
#sum
torch.sum(x)

tensor(7.2857)

In [122]:
# average
torch.mean(x)

tensor(0.4554)

In [123]:
# positional min - returns index of min value
torch.argmin(x)

tensor(15)

In [124]:
# x[0][4]

* Reshape - reshapes an input tensor to defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

Reshape (has to be compatible with size (no. of elements should remain same))

In [125]:
x = torch.arange(1.0,13.0)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [126]:
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

View

In [127]:
# changing z changes x
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [128]:
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

Stack tensors on top

In [129]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

# dim = 0 vstack
# dim = 1 htsack

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

Squeeze

In [130]:
x_try = torch.arange(1.,10.)
x_try

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [131]:
x_reshaped = x_try.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [132]:
x_reshaped.shape

torch.Size([1, 9])

In [133]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [134]:
x_reshaped.squeeze().shape

torch.Size([9])

Unsqueeze

In [135]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [136]:
x_unsqueezed.shape

torch.Size([9, 1])

Permute

In [137]:
x_original = torch.rand(size=(224,224,3))
x_original

tensor([[[0.8049, 0.4136, 0.9505],
         [0.8199, 0.0584, 0.3572],
         [0.5487, 0.8062, 0.2325],
         ...,
         [0.7658, 0.9510, 0.2529],
         [0.6475, 0.5427, 0.5481],
         [0.5946, 0.6918, 0.3092]],

        [[0.1031, 0.6904, 0.8118],
         [0.0942, 0.1426, 0.5775],
         [0.5247, 0.5826, 0.5827],
         ...,
         [0.0504, 0.5728, 0.6555],
         [0.6974, 0.1632, 0.9450],
         [0.3316, 0.1195, 0.8981]],

        [[0.6901, 0.9047, 0.7059],
         [0.8092, 0.9811, 0.8670],
         [0.8233, 0.9193, 0.3989],
         ...,
         [0.3692, 0.7339, 0.2405],
         [0.4717, 0.4833, 0.3484],
         [0.0617, 0.9536, 0.0898]],

        ...,

        [[0.0169, 0.5650, 0.6875],
         [0.0059, 0.2548, 0.9041],
         [0.5183, 0.7767, 0.7895],
         ...,
         [0.2978, 0.7938, 0.5681],
         [0.0760, 0.7132, 0.5136],
         [0.1920, 0.7748, 0.0625]],

        [[0.9411, 0.2168, 0.1661],
         [0.5358, 0.4563, 0.7245],
         [0.

In [139]:
x_permuted = x_original.permute(2,0,1)
# rearranging the indices - 2nd index first, 0th index second, 1st index third
x_permuted

tensor([[[0.8049, 0.8199, 0.5487,  ..., 0.7658, 0.6475, 0.5946],
         [0.1031, 0.0942, 0.5247,  ..., 0.0504, 0.6974, 0.3316],
         [0.6901, 0.8092, 0.8233,  ..., 0.3692, 0.4717, 0.0617],
         ...,
         [0.0169, 0.0059, 0.5183,  ..., 0.2978, 0.0760, 0.1920],
         [0.9411, 0.5358, 0.4511,  ..., 0.4648, 0.4910, 0.4931],
         [0.8052, 0.8498, 0.9521,  ..., 0.9804, 0.7560, 0.1030]],

        [[0.4136, 0.0584, 0.8062,  ..., 0.9510, 0.5427, 0.6918],
         [0.6904, 0.1426, 0.5826,  ..., 0.5728, 0.1632, 0.1195],
         [0.9047, 0.9811, 0.9193,  ..., 0.7339, 0.4833, 0.9536],
         ...,
         [0.5650, 0.2548, 0.7767,  ..., 0.7938, 0.7132, 0.7748],
         [0.2168, 0.4563, 0.7961,  ..., 0.5635, 0.5822, 0.3679],
         [0.8131, 0.6178, 0.1416,  ..., 0.6377, 0.8579, 0.1193]],

        [[0.9505, 0.3572, 0.2325,  ..., 0.2529, 0.5481, 0.3092],
         [0.8118, 0.5775, 0.5827,  ..., 0.6555, 0.9450, 0.8981],
         [0.7059, 0.8670, 0.3989,  ..., 0.2405, 0.3484, 0.

In [140]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [144]:
x_original[0,0,0] = 0.6969
x_original[0,0,0]

tensor(0.6969)

In [145]:
x_permuted[0,0,0] # x_permuted is a view of x_original and thus shares memory

tensor(0.6969)

<h3>Indexing Tensors</h3>

In [146]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [147]:
x[0] # we get what is inside first square bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [149]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [151]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [153]:
x[0,2,2]

tensor(9)

In [154]:
# Use : to select "all" from a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [155]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [156]:
x[:,1,1] # notice the square bracket

tensor([5])

In [158]:
x[0,0,:] # equivalent to x[0][0] or x[0,0]

tensor([1, 2, 3])

In [159]:
x[:,:,2]

tensor([[3, 6, 9]])

<h2>PyTorch Tensors and Numpy</h2>

Numpy is a powerful scientific numerical computing library, so PyTorch has functionality to interact with it

*   Convert data in numpy to PyTorch tensor -> torch.from_numpy(ndarray)
*   Convert PyTorch tensor to numpy array -> torch.Tensor.numpy()



In [160]:
import numpy as np

numpy array to tensor

In [161]:
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [163]:
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
tensor # new tensor in memory

# default tensor dtype is float32
# converting numpy array to tensor creates tensor of float64

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

tensor to numpy array

In [164]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # don't share memory

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

<h2>Reproducable random tensors</h2>

In [165]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6218, 0.9209, 0.2807, 0.5345],
        [0.3140, 0.1588, 0.9525, 0.3842],
        [0.2353, 0.6464, 0.8676, 0.7801]])
tensor([[0.4745, 0.7849, 0.6684, 0.1368],
        [0.2986, 0.0217, 0.3771, 0.9415],
        [0.6669, 0.5735, 0.2992, 0.8688]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [166]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


<h2>Setting up GPUs</h2>

*   Google Colab - Easy - Free to use, almost zero setup required, can share work with others as easy as a link - Doesn't save your data outputs, limited compute, subject to timeouts - (https://colab.research.google.com/notebooks/gpu.ipynb)
*   Use your own - Medium - Run everything locally on your own machine - GPUs aren't free, require upfront cost - (https://pytorch.org/get-started/locally/)
*   Cloud computing (AWS, GCP, Azure) - Medium-Hard - Small upfront cost, access to almost infinite compute -  Can get expensive if running continually, takes some time to setup right - (https://pytorch.org/get-started/cloud-partners/)

In [167]:
# check GPU access
torch.cuda.is_available()

False

In [169]:
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [170]:
# count no of devices (gpus)
torch.cuda.device_count()

0

In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available) - https://pytorch.org/docs/main/notes/cuda.html#device-agnostic-code

<h3>Putting tensors/models on the GPU</h3>

In [171]:
# creating a tensor on CPU
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [172]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

If tensor is on GPU, can't tconvert it to NumPy - that's one use case of why we need to take tensors back to CPU

In [ ]:
# move tensors back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

# tensor on gpu remains unchanged